### ISSUE TITLE
The program shows applying to jobs completed but no jobs are actually applied to

### ISSUE THREAD

**Issue by kevalhb** [feder-cr/Auto_Jobs_Applier_AIHawk#296]
## Description

I set up the program and ran it according to the instructions, it was successful in logging in -> navigating to the linkedIn jobs page -> scrolling through the page ; but I don't see any ongoing action after the message `Starting the application process for this page...` and after a couple of minutes it says `Applying to jobs on this page has been completed!` , but none of the jobs are actually applied to ; I am currently running it in the default mode `python main.py` where it should generate the resumes for me.

## Config used
```
remote: true

experienceLevel:
 internship: false 
 entry: true 
 associate: true
 mid-senior level: true
 director: false 
 executive: false 

jobTypes:
 full-time: true
 contract: true
 part-time: false 
 temporary: false 
 internship: false 
 other: false 
 volunteer: false 

date:
 all time: false 
 month: false
 week: false
 24 hours: true

positions:
  - Product Manager

locations:
  - United States

distance: 100

companyBlacklist:
  - Falkonry
  - Peloton
  - Helm.ai

titleBlacklist:
  - Sales
```
## Screenshot
![Screenshot 2024-09-05 at 4 30 05 PM](https://github.com/user-attachments/assets/b44cc888-4742-4e14-a739-e56b370477bc)

How do I fix this/proceed? Any debugging notes shall be helpful too.
