### ISSUE TITLE
Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'

### ISSUE THREAD

**Issue by hmm29** [feder-cr/Auto_Jobs_Applier_AIHawk#435]
### Describe the bug

Bot won't run: plain_text_resume.yaml 'education_level' field error. I get the following error even though I'm using proper yaml syntax and values based on the file in data_folder_examples.

### Steps to reproduce

Here's my yaml:

```
education_details:
  - education_level: "Bachelor's Degree"
    institution: "Yale University"
    field_of_study: "Computer Science & Psychology"
    # final_evaluation_grade: "[Not provided]"
    # start_date: "[Not provided]"
    graduation_year: "2017"
    # additional_info:
    #   exam: 
```

I watched the tutorial vid but don't see a lib_resume_builder package in my venv/lib folder.

When I run "python main.py" I get:

Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'
Check browser setup and other runtime issues.
Refer to the configuration and troubleshooting guide: https://github.com/feder-cr/LinkedIn_AIHawk_automatic_job_application/blob/main/readme.md#configuration

I've already tried switching to camelCase in case that would help but still get issues with other education_details fields. 

I noticed that @rezabanitaba had this issue too: https://github.com/feder-cr/Auto_Jobs_Applier_AIHawk/issues/402#issuecomment-2362820976

I don't want to include final_evaluation_grade

### Expected behavior

The bot would run

### Actual behavior

Runtime error: Error running the bot: Education.__init__() got an unexpected keyword argument 'education_level'

### Branch

main

### Python version

3.12.2

### LLM Used

OpenAI

### Model used

GPT-4o-mini

### Additional context

I've noticed that some yaml fields are camel case and others are snake case
